CREATE DATABASE PORTAL_ESTUDIANTIL;
USE PORTAL_ESTUDIANTIL;

CREATE TABLE registro(
	carnet INT NOT NULL,
	nombres VARCHAR(50) NOT NULL,
	apellidos VARCHAR(50) NOT NULL,
	contrasena VARCHAR(50) NOT NULL,
	correo VARCHAR(50) NOT NULL,
	PRIMARY KEY (carnet)
);


SELECT*FROM registro;




